print("Let's write a story")
Name = input("Write the name of a boy:")
day=input("another name for midday is:")
time=input("Write a midday time:")
animal=input("Write a fish name:")
object=input("write a fighting tool:")
word=input("Words you can use to appreciate someone:")


print("Story Time")
print("\033[33m", Name,"\033[0m","lives in village close to the sea.")
print("\033[34m","This was one of his favourite places to explore and play""\033[0m")
print("One",day," as he was playing by the river, he heard a splash and a cry for help")
print("It was around","\033[35m",time,"\033[0m","and the fishermen were not available")
print("He looked into the water and saw a young boy struggling and a huge","\033[32m",animal,"\033[0m","swimming towards him")
print("Without thinking","\033[33m",Name,"\033[0m","dove into the water with a","\033[31m",object,"\033[0m","swimming towards the struggling boy.")
print("\033[33m",Name,"\033[0m","was a fast swimmer and so he reached the boy just before the fish") 
print("He quickly threw the","\033[31m","\033[31m",object,"\033[0m","\033[0m","and caught the","\033[32m",animal,"\033[0m","in the eye")
print("The","\033[32m",animal,"\033[0m","was blinded with","\033[31m","pain","\033[0m","and immediately swam away")
print("Grabbing the boy's arms","\033[33m",Name,"\033[0m","fought the current and pulled him to shore")
print("Gasping for air, the boy whispered",word,"to","\033[33m",Name,"\033[0m")
print("From that day on","\033[33m",Name,"\033[0m","and the boy became good friends.")
print("\033[34m","and the sea was a reminder of their bond","\033[0m")
